### ISSUE TITLE
Shootable Rocket affected by other planet's Gravity

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/moonshot#1]
### Inspiration: [Angry birds space](https://www.youtube.com/watch?v=WKgGphfZXqA&ab_channel=AngryBirds)
![](https://media.giphy.com/media/Zk1KSOjisdfOZTA0IT/giphy.gif)

### Todo:

- [x] Have 1 object get gravitationally affected by others (can use `GravitationalBody.cs`) 
- [x] Allow ability to shoot pressing a key
- [x] Grow arrow to demonstrate force 
- [x] Start rocket from a circular planet? 

### Arrow growing demo:
![](https://media.giphy.com/media/ggeUBUCApiU6g8kaBN/giphy.gif)
