### ISSUE TITLE
Improve orbiting systems 

### ISSUE THREAD

**Issue by avivajpeyi** [avivajpeyi/moonshot#2]
## Current orbits:
<img width="158" alt="Screen Shot 2020-11-15 at 11 54 26 pm" src="https://user-images.githubusercontent.com/15642823/99185420-eaf1dc80-279d-11eb-898f-35b17635171b.png">

## Todo
- [x] Ensure orbiting planets dont overlap
- [x] Add multiple stars 
- [x] Add ability to alter trail (circles vs line trails)
